// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('@arco-design/web-vue')['Button']
    ACarousel: typeof import('@arco-design/web-vue')['Carousel']
    ACarouselItem: typeof import('@arco-design/web-vue')['CarouselItem']
    AConfigProvider: typeof import('@arco-design/web-vue')['ConfigProvider']
    AForm: typeof import('@arco-design/web-vue')['Form']
    AFormItem: typeof import('@arco-design/web-vue')['FormItem']
    AInput: typeof import('@arco-design/web-vue')['Input']
    AInputPassword: typeof import('@arco-design/web-vue')['InputPassword']
    AppVideoItem: typeof import('./components/app-video-item.vue')['default']
    ASpace: typeof import('@arco-design/web-vue')['Space']
    AStatistic: typeof import('@arco-design/web-vue')['Statistic']
    Border: typeof import('./components/border/index.vue')['default']
    Echarts: typeof import('./components/Echarts/index.vue')['default']
    'Index copy': typeof import('./components/Echarts/index copy.vue')['default']
    Line: typeof import('./components/Echarts/line.vue')['default']
    Logo: typeof import('./components/Logo/logo.vue')['default']
    Longjie: typeof import('./components/Longjie/index.vue')['default']
    PageMain: typeof import('./components/PageMain/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./components/SvgIcon/index.vue')['default']
  }
}
