// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core';

export {};

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppVideoItem: typeof import('./components/app-video-item.vue')['default'];
    Line: typeof import('./components/Echarts/line.vue')['default'];
    RouterLink: typeof import('vue-router')['RouterLink'];
    RouterView: typeof import('vue-router')['RouterView'];
    SvgIcon: typeof import('./components/SvgIcon/index.vue')['default'];
    VanSwipe: typeof import('vant/es')['Swipe'];
    VanSwipeItem: typeof import('vant/es')['SwipeItem'];
    VanTab: typeof import('vant/es')['Tab'];
    VanTabs: typeof import('vant/es')['Tabs'];
  }
}
